### ISSUE TITLE
Linter support

### ISSUE THREAD

**Issue by jreese** [facebookincubator/ptr#20]
## How is `ptr` not doing what you expect?

`ptr` doesn't support running linters.

## What is your suggestion to make this better?

I want to add support for flake8 and pylint.  I'm trying to decide if it's worth supporting linters as a general, configurable thing to run, or if I should just hardcode support for flake8 and pylint and call it a day.

**Comment by cooperlees** [comment]
Happy with hard coding today - But eventually I'd like to make `ptr` more like `flake8` in that it's more friendly for adding plugins and configuring the order things are run in. For Example:
- flake8, black, mypy + unit tests / coverage
- unit tests / coverage, flake8, black, mypy

I'm sure people will have opinions here ... But it seems a lot of work and not sure it's worth it.

**Comment by cooperlees** [comment]
Initial support merged. Lint away.
