### ISSUE TITLE
Move TravisCI tests to CircleCI / another Provider

### ISSUE THREAD

**Issue by cooperlees** [facebookincubator/ptr#61]
Facebook Open Source powers that be prefer our projects to not be on TravisCI. I like the ability to build with the latest Alpha, Beta + RC versions of Python and (if available) a build from Trunk to fix issues with newer versions of Python sooner rather than later.

It seems Azure is not keen on supporting this soonish, so I believe Circle CI will be the best alternative available today but open to other solutions to match the requests above.

## CircleCI Documentation:
- Python CI Example: https://circleci.com/docs/2.0/language-python/?gclid=EAIaIQobChMIg7PZxe2I5QIVFsRkCh2sIgXSEAAYASAAEgLPOvD_BwE#specify-a-version
- Docker Images: https://circleci.com/docs/2.0/circleci-images/?gclid=EAIaIQobChMI7NKc8O2I5QIV7x-tBh3eag3dEAAYASAAEgItaPD_BwE#python

(Azure Issue: https://github.com/microsoft/azure-pipelines-image-generation/issues/905)

**Comment by adhaamehab** [comment]
Hi, Can I start working on this?

**Comment by cooperlees** [comment]
Sure. If you can clone the TravisCI functionality to CircleCI or even Github Actions that would be great!

**Comment by cooperlees** [comment]
https://github.com/facebookincubator/ptr/commit/09d60edb1107a646e5f7b7ed3d57d474037403bc/checks

We ran, but have errors. I will eventually dog in and try fix it. But more PRs welcome if you have time and that it should now run on PRs / forks!

**Comment by cooperlees** [comment]
Low Pri: the badge in the README is not losing either ...

**Comment by adhaamehab** [comment]
Yeah sure, I'll work on fixing those errors in the next weekend :)
